// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVYJ4WSBNMY0Wl5NNj9BXN3tWm82ZBMJ4',
    appId: '1:605605598589:web:6d22be11e4e18f738e2814',
    messagingSenderId: '605605598589',
    projectId: 'learnfirebase-12098',
    authDomain: 'learnfirebase-12098.firebaseapp.com',
    storageBucket: 'learnfirebase-12098.appspot.com',
    measurementId: 'G-X1525R8SSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9iQ29OAzBtdAYzXzeHDspygL6Gfkd5E',
    appId: '1:605605598589:android:b1c2b36018305ae08e2814',
    messagingSenderId: '605605598589',
    projectId: 'learnfirebase-12098',
    storageBucket: 'learnfirebase-12098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColKfTgolU7gFP6-uLj_rY2LmlVu_y9bs',
    appId: '1:605605598589:ios:33f4871d9fb0ca408e2814',
    messagingSenderId: '605605598589',
    projectId: 'learnfirebase-12098',
    storageBucket: 'learnfirebase-12098.appspot.com',
    iosBundleId: 'com.example.learnfirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyColKfTgolU7gFP6-uLj_rY2LmlVu_y9bs',
    appId: '1:605605598589:ios:33f4871d9fb0ca408e2814',
    messagingSenderId: '605605598589',
    projectId: 'learnfirebase-12098',
    storageBucket: 'learnfirebase-12098.appspot.com',
    iosBundleId: 'com.example.learnfirebas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVYJ4WSBNMY0Wl5NNj9BXN3tWm82ZBMJ4',
    appId: '1:605605598589:web:1861c2dcf37a5f538e2814',
    messagingSenderId: '605605598589',
    projectId: 'learnfirebase-12098',
    authDomain: 'learnfirebase-12098.firebaseapp.com',
    storageBucket: 'learnfirebase-12098.appspot.com',
    measurementId: 'G-SV4BH9D1JB',
  );

}